#!/bin/bash
#
# Uploads the specified boxes to S3

set -eu -o pipefail

readonly BUCKET=${BUCKET:-tmatilai-vagrant}

usage() {
    echo "Usage: $0 box ..." >&2
    exit 64
}

upload() {
    aws s3 cp "$1" "s3://$BUCKET/" \
	--content-type application/octet-stream \
	--storage-class REDUCED_REDUNDANCY
    printf 'URL: http://%s.s3.amazonaws.com/%s\n\n' "$BUCKET" "$1"
}

main() {
    local box
    for box in "$@"; do
	upload "$box"
    done
}

if [[ $# = 0 ]] || [[ "$1" == -* ]]; then
    usage
fi

main "$@"
